# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mohsen/Projects/state.io

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mohsen/Projects/state.io

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mohsen/Projects/state.io/CMakeFiles /home/mohsen/Projects/state.io/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mohsen/Projects/state.io/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named state

# Build rule for target.
state: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 state
.PHONY : state

# fast build rule for target.
state/fast:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/build
.PHONY : state/fast

src/ai.o: src/ai.c.o

.PHONY : src/ai.o

# target to build an object file
src/ai.c.o:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/ai.c.o
.PHONY : src/ai.c.o

src/ai.i: src/ai.c.i

.PHONY : src/ai.i

# target to preprocess a source file
src/ai.c.i:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/ai.c.i
.PHONY : src/ai.c.i

src/ai.s: src/ai.c.s

.PHONY : src/ai.s

# target to generate assembly for a file
src/ai.c.s:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/ai.c.s
.PHONY : src/ai.c.s

src/events.o: src/events.c.o

.PHONY : src/events.o

# target to build an object file
src/events.c.o:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/events.c.o
.PHONY : src/events.c.o

src/events.i: src/events.c.i

.PHONY : src/events.i

# target to preprocess a source file
src/events.c.i:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/events.c.i
.PHONY : src/events.c.i

src/events.s: src/events.c.s

.PHONY : src/events.s

# target to generate assembly for a file
src/events.c.s:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/events.c.s
.PHONY : src/events.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/main.c.s
.PHONY : src/main.c.s

src/map.o: src/map.c.o

.PHONY : src/map.o

# target to build an object file
src/map.c.o:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/map.c.o
.PHONY : src/map.c.o

src/map.i: src/map.c.i

.PHONY : src/map.i

# target to preprocess a source file
src/map.c.i:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/map.c.i
.PHONY : src/map.c.i

src/map.s: src/map.c.s

.PHONY : src/map.s

# target to generate assembly for a file
src/map.c.s:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/map.c.s
.PHONY : src/map.c.s

src/potion.o: src/potion.c.o

.PHONY : src/potion.o

# target to build an object file
src/potion.c.o:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/potion.c.o
.PHONY : src/potion.c.o

src/potion.i: src/potion.c.i

.PHONY : src/potion.i

# target to preprocess a source file
src/potion.c.i:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/potion.c.i
.PHONY : src/potion.c.i

src/potion.s: src/potion.c.s

.PHONY : src/potion.s

# target to generate assembly for a file
src/potion.c.s:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/potion.c.s
.PHONY : src/potion.c.s

src/soldier.o: src/soldier.c.o

.PHONY : src/soldier.o

# target to build an object file
src/soldier.c.o:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/soldier.c.o
.PHONY : src/soldier.c.o

src/soldier.i: src/soldier.c.i

.PHONY : src/soldier.i

# target to preprocess a source file
src/soldier.c.i:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/soldier.c.i
.PHONY : src/soldier.c.i

src/soldier.s: src/soldier.c.s

.PHONY : src/soldier.s

# target to generate assembly for a file
src/soldier.c.s:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/soldier.c.s
.PHONY : src/soldier.c.s

src/ui.o: src/ui.c.o

.PHONY : src/ui.o

# target to build an object file
src/ui.c.o:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/ui.c.o
.PHONY : src/ui.c.o

src/ui.i: src/ui.c.i

.PHONY : src/ui.i

# target to preprocess a source file
src/ui.c.i:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/ui.c.i
.PHONY : src/ui.c.i

src/ui.s: src/ui.c.s

.PHONY : src/ui.s

# target to generate assembly for a file
src/ui.c.s:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/src/ui.c.s
.PHONY : src/ui.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... state"
	@echo "... src/ai.o"
	@echo "... src/ai.i"
	@echo "... src/ai.s"
	@echo "... src/events.o"
	@echo "... src/events.i"
	@echo "... src/events.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/potion.o"
	@echo "... src/potion.i"
	@echo "... src/potion.s"
	@echo "... src/soldier.o"
	@echo "... src/soldier.i"
	@echo "... src/soldier.s"
	@echo "... src/ui.o"
	@echo "... src/ui.i"
	@echo "... src/ui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

